openapi: '3.0.3'
info:
  title: NewsMirror API
  description: NewsMirror API
  version: 1.0.0
servers:
  - url: /api
    description: server

paths:
  '/info':
    get:
      tags:
        - dummy
      summary: Get Dummy Info
      operationId: getInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/info'


components:
  schemas:
    info:
      type: object
      properties:
        version:
          type: string
        description:
          type: string